# Generated by Django 4.1.3 on 2022-11-09 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('Cleaning ', 'Cleaning'), ('Panatary ', 'Panatary'), ('General', 'General')], default='Cleaning', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='product_img')),
                ('product_img_icon', models.ImageField(blank=True, null=True, upload_to='product_img_icon')),
                ('price', models.PositiveIntegerField()),
                ('quantity_label', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
